[package]
name = "vermillion"
description = "Diesel Schema Parser and Model Generator"
version = "0.1.0"
authors = ["hgking <hgmaxwellking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
